# Generated by Django 6.0.6 on 2026-06-09 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=500)),
                ('dblp_key', models.CharField(blank=True, max_length=100, null=True)),
                ('core_rank', models.CharField(max_length=10)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('orcid', models.CharField(blank=True, max_length=100, null=True)),
                ('dblp_pid', models.CharField(blank=True, max_length=100, null=True)),
                ('irins_id', models.CharField(blank=True, max_length=100, null=True)),
                ('homepage', models.URLField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty', to='api.department')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='api.institution')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='api.institution'),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('year', models.IntegerField()),
                ('doi', models.CharField(blank=True, max_length=255, null=True)),
                ('dblp_key', models.CharField(blank=True, max_length=255, null=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='api.conference')),
            ],
        ),
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.FloatField(default=1.0)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorships', to='api.faculty')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorships', to='api.publication')),
            ],
            options={
                'unique_together': {('faculty', 'publication')},
            },
        ),
    ]
