# Generated by Django 6.0.6 on 2026-06-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='is_workshop',
            field=models.BooleanField(default=False, help_text='True if publication is <= 5 pages'),
        ),
        migrations.AddField(
            model_name='publication',
            name='page_count',
            field=models.IntegerField(blank=True, help_text='Number of pages in the publication', null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='dblp_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
