# Generated by Django 6.0.6 on 2026-08-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_publication_is_workshop_publication_page_count_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authorship',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='conference',
            name='acronym',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='conference',
            index=models.Index(fields=['area'], name='conference_area_idx'),
        ),
        migrations.AddIndex(
            model_name='conference',
            index=models.Index(fields=['core_rank'], name='conference_core_rank_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['year'], name='publication_year_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['is_workshop', 'year'], name='publication_workshop_year_idx'),
        ),
        migrations.AddConstraint(
            model_name='authorship',
            constraint=models.UniqueConstraint(fields=('faculty', 'publication'), name='authorship_unique_faculty_publication'),
        ),
        migrations.AddConstraint(
            model_name='authorship',
            constraint=models.CheckConstraint(condition=models.Q(('credit__gt', 0), ('credit__lte', 1)), name='authorship_credit_is_a_fraction'),
        ),
        migrations.AddConstraint(
            model_name='conference',
            constraint=models.UniqueConstraint(condition=models.Q(('dblp_key', ''), _negated=True), fields=('dblp_key',), name='conference_unique_dblp_key_when_set'),
        ),
        migrations.AddConstraint(
            model_name='conference',
            constraint=models.CheckConstraint(condition=models.Q(('core_rank__in', ['A*', 'A', 'Journal'])), name='conference_core_rank_domain'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='department_unique_name_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='faculty',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='faculty_unique_name_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='faculty',
            constraint=models.UniqueConstraint(condition=models.Q(('dblp_pid', ''), _negated=True), fields=('dblp_pid',), name='faculty_unique_dblp_pid_when_set'),
        ),
        migrations.AddConstraint(
            model_name='publication',
            constraint=models.UniqueConstraint(fields=('title', 'year', 'conference'), name='publication_unique_title_year_venue'),
        ),
        migrations.AddConstraint(
            model_name='publication',
            constraint=models.CheckConstraint(condition=models.Q(('year__gte', 1900), ('year__lte', 2100)), name='publication_year_range'),
        ),
        migrations.AddConstraint(
            model_name='publication',
            constraint=models.CheckConstraint(condition=models.Q(('page_count__isnull', True), ('page_count__gt', 0), _connector='OR'), name='publication_page_count_positive'),
        ),
    ]
