# Generated by Django 6.0.6 on 2026-08-04 12:47

from django.db import migrations, models

# Columns converted from "nullable text" to "NOT NULL, defaults to ''".
# Existing NULLs have to become '' before the NOT NULL alteration runs, or the
# table rebuild rejects them.
NULLABLE_TEXT_COLUMNS = [
    ('api_conference', 'dblp_key'),
    ('api_faculty', 'dblp_pid'),
    ('api_faculty', 'designation'),
    ('api_faculty', 'homepage'),
    ('api_faculty', 'irins_id'),
    ('api_faculty', 'orcid'),
    ('api_institution', 'city'),
    ('api_institution', 'state'),
    ('api_institution', 'website'),
    ('api_publication', 'dblp_key'),
    ('api_publication', 'doi'),
]


def blank_out_nulls(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        for table, column in NULLABLE_TEXT_COLUMNS:
            cursor.execute(
                f'UPDATE "{table}" SET "{column}" = %s WHERE "{column}" IS NULL', ['']
            )


def restore_nulls(apps, schema_editor):
    """Put NULLs back so the columns can be nullable again.

    Needed for more than tidiness: reversing the first operation below restores
    the old field-level UNIQUE index on publication.dblp_key, which only ever
    held because every row was NULL. Leaving 3325 empty strings in place would
    collide the moment that index is recreated. The original mixture of NULL and
    '' cannot be recovered — that ambiguity is exactly what this migration
    removed — so every empty string goes back to NULL.
    """
    with schema_editor.connection.cursor() as cursor:
        for table, column in NULLABLE_TEXT_COLUMNS:
            cursor.execute(f'UPDATE "{table}" SET "{column}" = NULL WHERE "{column}" = %s', [''])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_declare_candidate_keys_and_indexes'),
    ]

    operations = [
        # Must come first. publication.dblp_key still carries the old
        # field-level UNIQUE index, which was satisfied only because every row
        # was NULL; blanking those NULLs to '' would collide immediately. Drop
        # the index (still nullable at this point), then blank, then tighten to
        # NOT NULL below. The partial UNIQUE added at the end is the constraint
        # that actually enforces anything.
        migrations.AlterField(
            model_name='publication',
            name='dblp_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(blank_out_nulls, restore_nulls),
        migrations.AlterField(
            model_name='conference',
            name='dblp_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='dblp_pid',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='homepage',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='irins_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='orcid',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='institution',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='institution',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='institution',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='publication',
            name='dblp_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='publication',
            constraint=models.UniqueConstraint(condition=models.Q(('dblp_key', ''), _negated=True), fields=('dblp_key',), name='publication_unique_dblp_key_when_set'),
        ),
    ]
