# Generated by Django 6.0.6 on 2026-08-04 12:51

import django.db.models.deletion
from django.db import migrations, models

# Inlined rather than imported from api.reference_data: a migration has to keep
# replaying correctly years from now, and application code will have moved on.
FOR_DESCRIPTIONS = {
    '4601': 'Applied Computing',
    '4602': 'Artificial Intelligence',
    '4603': 'Computer Vision & Multimedia',
    '4604': 'Cybersecurity and Privacy',
    '4605': 'Data Management and Data Science',
    '4606': 'Distributed Computing',
    '4607': 'Graphics, Augmented Reality and Games',
    '4608': 'Human-Centred Computing',
    '4609': 'Information Systems',
    '4610': 'Library and Information Studies',
    '4611': 'Machine Learning',
    '4612': 'Software Engineering',
    '4613': 'Theory of Computation',
}

RANK_WEIGHTS = {'A*': 4.0, 'A': 2.0, 'Journal': 1.0}


def area_slug(name):
    return name.lower().replace(' ', '_').replace('&', 'and').replace(',', '')


def seed_reference_data(apps, schema_editor):
    """Populate the reference tables before the foreign keys point at them.

    Every area code and rank already present on a conference row must have a
    matching row here, or the foreign key alterations below fail.
    """
    Conference = apps.get_model('api', 'Conference')
    RankTier = apps.get_model('api', 'RankTier')
    ResearchArea = apps.get_model('api', 'ResearchArea')

    for code, weight in RANK_WEIGHTS.items():
        RankTier.objects.update_or_create(code=code, defaults={'weight': weight})

    # Any rank in the data that the scheme above does not know about still needs
    # a row; weight 1.0 matches the old `default=Value(1.0)` fallback.
    for code in Conference.objects.exclude(core_rank='').values_list('core_rank', flat=True).distinct():
        RankTier.objects.get_or_create(code=code, defaults={'weight': 1.0})

    for code, name in FOR_DESCRIPTIONS.items():
        ResearchArea.objects.update_or_create(
            code=code, defaults={'name': name, 'slug': area_slug(name)},
        )

    # Codes that appear on venues but have no published name fall back to the
    # code itself, which is exactly what views.py did with FOR_DESCRIPTIONS.get.
    used = Conference.objects.filter(area__isnull=False).exclude(area='')
    for code in used.values_list('area', flat=True).distinct():
        ResearchArea.objects.get_or_create(
            code=code, defaults={'name': code, 'slug': area_slug(code)},
        )


def unseed_reference_data(apps, schema_editor):
    apps.get_model('api', 'RankTier').objects.all().delete()
    apps.get_model('api', 'ResearchArea').objects.all().delete()


def backfill_venue_type(apps, schema_editor):
    """Split the venue kind back out of the rank column."""
    Conference = apps.get_model('api', 'Conference')
    Conference.objects.filter(core_rank='Journal').update(venue_type='journal')
    Conference.objects.exclude(core_rank='Journal').update(venue_type='conference')


def noop_reverse(apps, schema_editor):
    """venue_type is dropped by the reverse of AddField; nothing to undo."""


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_single_empty_state_for_optional_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankTier',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('weight', models.FloatField()),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ResearchArea',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.RunPython(seed_reference_data, unseed_reference_data),
        # The CHECK on core_rank's domain is superseded by the foreign key
        # below, which enforces the same thing by reference instead.
        migrations.RemoveConstraint(
            model_name='conference',
            name='conference_core_rank_domain',
        ),
        migrations.AddField(
            model_name='conference',
            name='venue_type',
            field=models.CharField(choices=[('conference', 'Conference'), ('journal', 'Journal')], default='conference', max_length=20),
        ),
        migrations.RunPython(backfill_venue_type, noop_reverse),
        migrations.AlterField(
            model_name='conference',
            name='core_rank',
            field=models.ForeignKey(db_column='core_rank', on_delete=django.db.models.deletion.PROTECT, related_name='conferences', to='api.ranktier'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='area',
            field=models.ForeignKey(blank=True, db_column='area', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conferences', to='api.researcharea'),
        ),
    ]
