# Generated by Django 6.0.6 on 2026-08-04 12:54

from django.db import migrations, models

DOI_URL_PREFIXES = ('https://doi.org/', 'http://doi.org/', 'https://dx.doi.org/', 'http://dx.doi.org/')


def backfill_author_count(apps, schema_editor):
    """Recover num_authors from the credit already stored on the authorships.

    credit was written as 1/num_authors rounded to four places, so inverting and
    rounding recovers the original count exactly for any realistic author count.
    """
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            UPDATE api_publication
               SET num_authors = (
                   SELECT CAST(ROUND(1.0 / a.credit) AS INTEGER)
                     FROM api_authorship a
                    WHERE a.publication_id = api_publication.id
                    LIMIT 1
               )
             WHERE num_authors IS NULL
            """
        )


def split_doi_and_url(apps, schema_editor):
    """Separate the bare DOI from the electronic-edition link.

    The `doi` column was filled from DBLP's <ee> element, which is a DOI URL for
    some venues and a publisher/anthology URL for others, so the column held
    both a DOI and, more often, something that was not one.
    """
    Publication = apps.get_model('api', 'Publication')

    for pk, doi in Publication.objects.exclude(doi='').values_list('id', 'doi').iterator():
        stripped = None
        for prefix in DOI_URL_PREFIXES:
            if doi.startswith(prefix):
                stripped = doi[len(prefix):]
                break

        if stripped is not None:
            # A DOI wearing a URL: keep both halves.
            Publication.objects.filter(pk=pk).update(doi=stripped, ee_url=doi)
        elif doi.startswith('http'):
            # Not a DOI at all — an anthology or publisher link.
            Publication.objects.filter(pk=pk).update(doi='', ee_url=doi)
        else:
            # Already a bare DOI; reconstruct the link it resolves through.
            Publication.objects.filter(pk=pk).update(ee_url=f'https://doi.org/{doi}')


def unsplit_doi_and_url(apps, schema_editor):
    """Put the ee link back in `doi`, which is what the column used to hold."""
    Publication = apps.get_model('api', 'Publication')
    for pk, doi, ee_url in Publication.objects.values_list('id', 'doi', 'ee_url').iterator():
        if not ee_url:
            continue
        restored = doi if doi and ee_url.endswith(doi) else ee_url
        Publication.objects.filter(pk=pk).update(doi=restored)


def noop_reverse(apps, schema_editor):
    """num_authors is dropped by the reverse of AddField; nothing to undo."""


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reference_tables_for_areas_and_ranks'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='ee_url',
            field=models.URLField(blank=True, default='', help_text='Electronic edition link as published by DBLP', max_length=500),
        ),
        migrations.AddField(
            model_name='publication',
            name='num_authors',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Total authors on the paper, including those outside the roster', null=True),
        ),
        migrations.RunPython(backfill_author_count, noop_reverse),
        # Must precede the CHECK that forbids a URL in `doi`.
        migrations.RunPython(split_doi_and_url, unsplit_doi_and_url),
        migrations.AlterField(
            model_name='publication',
            name='is_workshop',
            field=models.BooleanField(default=False, help_text='Classified as a workshop/adjunct paper rather than a main-track one'),
        ),
        migrations.AddConstraint(
            model_name='publication',
            constraint=models.CheckConstraint(condition=models.Q(('num_authors__isnull', True), ('num_authors__gte', 1), _connector='OR'), name='publication_num_authors_positive'),
        ),
        migrations.AddConstraint(
            model_name='publication',
            constraint=models.CheckConstraint(condition=models.Q(('doi__startswith', 'http'), _negated=True), name='publication_doi_is_not_a_url'),
        ),
    ]
