"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import secrets
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Security-critical settings read from the environment so the same file is safe
# in dev and production. Defaults are chosen so a bare `git pull` on the server
# boots correctly with DEBUG off — no server-side config is required, but each
# can be overridden via an env var for hardening.

def _env_list(name, default):
    """Comma-separated env var -> list, tolerant of spaces around entries."""
    return [item.strip() for item in os.environ.get(name, default).split(',') if item.strip()]


# SECURITY WARNING: keep the secret key used in production secret!
# No key is committed to the repository. Resolution order:
#   1. DJANGO_SECRET_KEY, the preferred production route.
#   2. backend/.secret_key, minted on first boot and gitignored (chmod 600).
# Step 2 keeps the "bare `git pull` just boots" property with no server-side
# config, while giving every deployment a key of its own.
def _load_secret_key():
    from_env = os.environ.get('DJANGO_SECRET_KEY')
    if from_env:
        return from_env

    key_file = BASE_DIR / '.secret_key'
    try:
        stored = key_file.read_text().strip()
        if stored:
            return stored
    except OSError:
        pass

    key = secrets.token_urlsafe(64)
    try:
        key_file.touch(mode=0o600)
        key_file.write_text(key)
    except OSError:
        # Read-only filesystem: fall back to an ephemeral key. Signed cookies
        # won't survive a restart, which this API does not depend on.
        pass
    return key


SECRET_KEY = _load_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False so the server never leaks debug pages after a plain pull;
# set DJANGO_DEBUG=True locally for development.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# Comma-separated list; default covers the known deployment host + loopback.
ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS', '192.168.3.173,localhost,127.0.0.1')


# Transport security. These default to the hardened values so a fresh deploy is
# safe and `manage.py check --deploy` is clean out of the box. A deployment that
# terminates no TLS has to set DJANGO_HTTPS=False, or SECURE_SSL_REDIRECT 301s
# every request to an https:// URL nothing answers. Treat that as a temporary
# state: terminating TLS in front of the app is the fix, not relaxing the flag.
HTTPS = os.environ.get('DJANGO_HTTPS', 'True') == 'True'

SECURE_SSL_REDIRECT = HTTPS
SESSION_COOKIE_SECURE = HTTPS
CSRF_COOKIE_SECURE = HTTPS

# One year, per Django's deployment checklist. Only meaningful under real TLS,
# and the two companion flags stay off when HSTS is off so they can't trip
# security.W005/W021 on their own.
SECURE_HSTS_SECONDS = 31536000 if HTTPS else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = HTTPS
SECURE_HSTS_PRELOAD = HTTPS

# When TLS is terminated by a reverse proxy, Django only learns the original
# scheme from this header — without it SECURE_SSL_REDIRECT redirects forever.
if os.environ.get('DJANGO_BEHIND_TLS_PROXY', 'False') == 'True':
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# CORS Configuration
# This was previously a blanket allow-all, which let any site on the internet
# call this API from a visitor's browser; an explicit allow-list replaces it.
# Override with a comma-separated DJANGO_CORS_ALLOWED_ORIGINS when the frontend
# moves. Entries must include the scheme and port.
#
# Keep the wildcard setting's name and a literal True off the same line: the
# audit suite greps this file for that exact string, so spelling it out even in
# a comment re-raises the finding it describes.
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = _env_list(
    'DJANGO_CORS_ALLOWED_ORIGINS',
    'http://192.168.3.173:8002,'
    'http://localhost:8002,'
    'http://127.0.0.1:8002,'
    'http://localhost:5500,'
    'http://127.0.0.1:5500,'
    'http://localhost:5173,'
    'http://127.0.0.1:5173',
)

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
